name: update my language

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "30 * * * *"


jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: 80c337d3-a4df-4e70-a117-e6b8f62c8dc3
          SHOW_TITLE:  true
          HEAD_FLAG:  true 
