# This is a basic workflow to help you get started with Actions

name: update my language


on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "30 * * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: Shadow-Java/README@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE:   true
